apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  glusterfs: 
    endpoints: glusterfs-cluster 
    path: dev-app 
    readOnly: false
  persistentVolumeReclaimPolicy: Retain     
