apiVersion: v1
kind: ReplicationController
metadata:
  name: app-rc
  namespace: app
spec:
  replicas: {{ app_replicas }}
  template:
    metadata:
      labels:
        app: app
    spec:
      volumes:
        - name: app-pv
          persistentVolumeClaim:
            claimName: app-pvc
        - name: props
          configMap:
            name: app-cm
      containers:
        - name: app
          image: {{ docker_registry }}/app:{{ app_version }}
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "java $JAVA_OPTS -jar /opt/app/app.jar" ]
          volumeMounts:
            - name: app-pv
              mountPath: "/share/logs"
            - name: props
              mountPath: "/opt/app/props"
          env:
            - name: CONTAINER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JAVA_OPTS
              value: -Xms256m -Xmx1024m -Dspring.config.location=/opt/app/props/application.properties 
          resources:
            limits:
              memory: {{ memory_limit }}
              cpu: {{ cpu_limit }}
            requests:
              memory: {{ memory_request }}
              cpu: {{ cpu_request }}
          lifecycle:
            preStop:
              exec:
                command:
                  - "touch"
                  - "/tmp/container-stop"
          livenessProbe:
            httpGet:
              path: /alive
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 300
            failureThreshold: 3
            timeoutSeconds: 60
      terminationGracePeriodSeconds: 300